version: '3.8'

services:
  app:
    build: .
    container_name: user_service_api
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - HTTP_PORT=8080
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
    command: ["/app/api"]

  worker:
    build: .
    container_name: user_service_worker
    environment:
      - DB_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    command: ["/app/worker"]

  postgres:
    image: postgres:16
    container_name: user_service_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: user_service_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    container_name: user_service_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
